In [ ]:
from scipy.io import loadmat
from pathlib import Path
import glob, os
import numpy as np



In [11]:
data = loadmat("bead_280.mat")

In [13]:
#x,y,stvarni frame, broj čestice, korak unutar putanje
data['bsec']

array([[ 22.9647201 , 213.90688729, 404.        , 280.        ,
          1.        ],
       [ 22.96492901, 213.94901696, 405.        , 280.        ,
          2.        ],
       [ 22.96513792, 213.99114663, 406.        , 280.        ,
          3.        ],
       [ 22.94678222, 214.00344989, 407.        , 280.        ,
          4.        ],
       [ 22.92842653, 214.01575315, 408.        , 280.        ,
          5.        ],
       [ 22.8663053 , 213.83845193, 409.        , 280.        ,
          6.        ],
       [ 22.9079473 , 213.93084082, 410.        , 280.        ,
          7.        ],
       [ 22.92635646, 213.95883386, 411.        , 280.        ,
          8.        ],
       [ 23.01720088, 214.08921661, 412.        , 280.        ,
          9.        ],
       [ 22.94492222, 213.97028489, 413.        , 280.        ,
         10.        ],
       [ 22.95014187, 213.95412928, 414.        , 280.        ,
         11.        ],
       [ 22.90309311, 213.92109008, 415.   

In [2]:
data = loadmat(r"C:\Users\dujme\Desktop\Seminar_venv\10rad_60perc_echo1\bead_1.mat")
#x,y,stvarni frame, broj čestice, korak unutar putanje
data['bsec']

array([[400.80756161, 154.43394935,   1.        ,   1.        ,
          1.        ],
       [400.77725766, 154.42783719,   2.        ,   1.        ,
          2.        ],
       [400.79815411, 154.40841833,   3.        ,   1.        ,
          3.        ],
       [400.7450995 , 154.38082437,   4.        ,   1.        ,
          4.        ],
       [400.78079129, 154.27481108,   5.        ,   1.        ,
          5.        ],
       [400.77535135, 154.35076543,   6.        ,   1.        ,
          6.        ],
       [400.87369273, 154.46953263,   7.        ,   1.        ,
          7.        ],
       [400.86315974, 154.5413102 ,   8.        ,   1.        ,
          8.        ],
       [400.90923467, 154.4080451 ,   9.        ,   1.        ,
          9.        ],
       [401.0502517 , 154.62393202,  10.        ,   1.        ,
         10.        ],
       [401.16299013, 154.55382452,  11.        ,   1.        ,
         11.        ],
       [401.09069666, 154.49546913,  12.   

In [3]:
data = loadmat(r"C:\Users\dujme\Desktop\Seminar_venv\10rad_60perc_echo2\bead_1.mat")
#x,y,stvarni frame, broj čestice, korak unutar putanje
data['bsec']

array([[ 53.17098555,  98.86410559,   4.        ,   1.        ,
          1.        ],
       [ 53.40065934,  98.89433731,   5.        ,   1.        ,
          2.        ],
       [ 53.63033312,  98.92456903,   6.        ,   1.        ,
          3.        ],
       [ 53.86000691,  98.95480075,   7.        ,   1.        ,
          4.        ],
       [ 53.95368945,  98.97330395,   8.        ,   1.        ,
          5.        ],
       [ 54.04737198,  98.99180716,   9.        ,   1.        ,
          6.        ],
       [ 54.14105452,  99.01031036,  10.        ,   1.        ,
          7.        ],
       [ 53.98819844,  98.92052665,  11.        ,   1.        ,
          8.        ],
       [ 54.00250036,  99.09670903,  12.        ,   1.        ,
          9.        ],
       [ 54.10021244,  99.05145986,  13.        ,   1.        ,
         10.        ],
       [ 54.19792453,  99.00621068,  14.        ,   1.        ,
         11.        ],
       [ 54.29563662,  98.96096151,  15.   

In [4]:
data = loadmat(r"C:\Users\dujme\Desktop\Seminar_venv\10rad_60perc_echo3\bead_1.mat")
#x,y,stvarni frame, broj čestice, korak unutar putanje
data['bsec']

array([[192.92946208, 188.31712646,   1.        ,   1.        ,
          1.        ],
       [192.96366714, 188.32586797,   2.        ,   1.        ,
          2.        ],
       [193.24605549, 188.31153919,   3.        ,   1.        ,
          3.        ],
       [193.38058501, 188.26490062,   4.        ,   1.        ,
          4.        ],
       [193.3653235 , 188.40181667,   5.        ,   1.        ,
          5.        ],
       [193.44384556, 188.32564938,   6.        ,   1.        ,
          6.        ],
       [193.57858654, 188.30085671,   7.        ,   1.        ,
          7.        ],
       [193.41347229, 188.35364897,   8.        ,   1.        ,
          8.        ],
       [193.5060877 , 188.37766973,   9.        ,   1.        ,
          9.        ],
       [193.45328957, 188.31567415,  10.        ,   1.        ,
         10.        ],
       [193.41396568, 188.36277515,  11.        ,   1.        ,
         11.        ],
       [193.55223273, 188.30580786,  12.   

In [18]:
fov_dir = r"C:\Users\dujme\Desktop\Seminar_venv\10rad_60perc_echo5"
n= len(glob.glob(os.path.join(fov_dir, "*.mat")))
b=0
for i in range(1,n-1):
    data = loadmat(fr"C:\Users\dujme\Desktop\Seminar_venv\10rad_60perc_echo5\bead_{i}.mat")
    if len(data['bsec']) == 599:
        b=b+1
    print(i,len(data['bsec']))
print('broj koji ima 599 podataka:', b)

1 106
2 116
3 126
4 126
5 121
6 120
7 128
8 144
9 144
10 146
11 143
12 157
13 149
14 176
15 162
16 156
17 182
18 182
19 195
20 190
21 188
22 187
23 186
24 180
25 148
26 128
27 128
28 201
29 201
30 202
31 207
32 186
33 152
34 114
35 231
36 226
37 228
38 225
39 187
40 138
41 240
42 243
43 239
44 241
45 244
46 231
47 240
48 152
49 266
50 273
51 263
52 221
53 196
54 284
55 298
56 317
57 302
58 308
59 144
60 120
61 329
62 333
63 331
64 226
65 349
66 350
67 346
68 345
69 342
70 352
71 234
72 121
73 117
74 358
75 362
76 168
77 131
78 393
79 134
80 414
81 204
82 196
83 138
84 434
85 425
86 373
87 278
88 240
89 211
90 156
91 215
92 136
93 474
94 464
95 460
96 324
97 173
98 123
99 496
100 487
101 478
102 323
103 121
104 249
105 249
106 239
107 210
108 190
109 118
110 534
111 534
112 537
113 163
114 136
115 117
116 554
117 453
118 232
119 162
120 151
121 164
122 155
123 563
124 510
125 507
126 345
127 324
128 161
129 129
130 269
131 238
132 209
133 169
134 143
135 599
136 599
137 598
138 599
139 

In [ ]:
import numpy as np

b = loadmat(r"C:\Users\dujme\Desktop\Seminar_venv\10rad_60perc_echo2\bead_1.mat")["bsec"]
d = np.diff(b[:,2])
print(np.unique(d)[:10], np.median(d))

[1.] 1.0


In [6]:
len(b)

113

In [1]:
import glob
import os
import numpy as np
from scipy.io import loadmat

def echo_length(echo_dir):
    mats = glob.glob(os.path.join(echo_dir, "bead_*.mat"))
    max_frame = 0
    for p in mats:
        b = loadmat(p)["bsec"]
        max_frame = max(max_frame, int(np.max(b[:,2])))
    return len(mats), max_frame

base = r"C:\Users\dujme\Desktop\Seminar_venv"
for k in range(1, 13):
    d = os.path.join(base, f"10rad_60perc_echo{k}")
    n_beads, n_frames = echo_length(d)
    print(k, n_beads, n_frames)

1 1 102
2 1 116
3 1 106
4 0 0
5 416 599
6 0 0
7 0 0
8 0 0
9 0 0
10 0 0
11 0 0
12 0 0


In [8]:
import glob, os
fov_dir = r"C:\Users\dujme\Desktop\dipl\example particle tracking data eva\highrange echo 10 rad_s 60perc\fov1"
print(len(glob.glob(os.path.join(fov_dir, "*.tif"))))

599


In [11]:
import glob, os
fov_dir = r"C:\Users\dujme\Desktop\Seminar_venv\10rad_60perc_echo5"
print(len(glob.glob(os.path.join(fov_dir, "*.mat"))))

418
